name: tensorflow2
dependencies:
- funcsigs=1.0.2=py27_0
- libgfortran=3.0.0=1
- mkl=11.3.3=0
- mock=2.0.0=py27_0
- ncurses=5.9=9
- numpy=1.11.2=py27_0
- openssl=1.0.2j=0
- pandas=0.19.0=np111py27_0
- pbr=1.10.0=py27_0
- pip=8.1.2=py27_0
- protobuf=3.0.0b2=py27_0
- python=2.7.12=1
- python-dateutil=2.5.3=py27_0
- pytz=2016.7=py27_0
- readline=6.2=2
- scikit-learn=0.18=np111py27_0
- scipy=0.18.1=np111py27_0
- setuptools=27.2.0=py27_0
- six=1.10.0=py27_1
- sqlite=3.13.0=0
- tensorflow=0.10.0=py27_0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - certifi==2016.9.26
  - configparser==3.5.0
  - cycler==0.10.0
  - decorator==4.0.10
  - entrypoints==0.2.2
  - enum34==1.1.6
  - functools32==3.2.3.post2
  - ipykernel==4.5.0
  - ipython==5.1.0
  - ipython-genutils==0.1.0
  - ipywidgets==5.2.2
  - jinja2==2.8
  - jsonschema==2.5.1
  - jupyter==1.0.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - markupsafe==0.23
  - matplotlib==1.5.3
  - mistune==0.7.3
  - nbconvert==4.2.0
  - nbformat==4.1.0
  - nltk==3.2.1
  - notebook==4.2.3
  - pathlib2==2.1.0
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - prompt-toolkit==1.0.8
  - ptyprocess==0.5.1
  - pygments==2.1.3
  - pyparsing==2.1.10
  - pyzmq==16.0.0
  - qtconsole==4.2.1
  - simplegeneric==0.8.1
  - singledispatch==3.4.0.3
  - sklearn==0.0
  - terminado==0.6
  - tornado==4.4.2
  - traitlets==4.3.1
  - wcwidth==0.1.7
  - widgetsnbextension==1.2.6

